name: Build and Deploy Github&Gitee Pages

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - .gitignore
      - .editorconfig

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.4'

      - name: Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
            source-repo: "git@github.com:luizyao/pytest-pyppeteer.git"
            destination-repo: "git@gitee.com:luizyao/pytest-pyppeteer.git"
